spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:h2:tcp://localhost/~/backendproj
=======
    url: jdbc:h2:tcp://localhost/~/spring-proj
>>>>>>> c9afede (66l)
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
  #      show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace